import { useEffect, useRef, useState, type ReactNode } from "react";
import { AnimatePresence, motion, useInView } from "framer-motion";
import { ArrowDownRight, ArrowRight, BarChart3, Check, Code2, Database, ExternalLink, Github, Linkedin, Mail, Menu, Phone, Send, Server, Sparkles, X } from "lucide-react";

const profile = { name:"Ahmed Abozead", role:"Data Engineer", email:"ahmednb34963@gmail.com", phone:"01065935958", location:"Cairo, Egypt", linkedin:"https://www.linkedin.com/in/ahmed-abozead", github:"https://github.com/ahmedabozead" };
const projects = [
 {id:"sales",n:"01",type:"ETL PIPELINE",title:"Sales Data Engineering ETL Pipeline",desc:"Built an end-to-end batch ETL pipeline to ingest, transform, validate, and load customer, product, and sales data.",tech:["Python","Pandas","SQLite","SQL Server","SQL","Git/GitHub"],github:"https://github.com/ahmedabozead/sales-data-engineering",features:["Processed 10,003 sales records","Produced 9,774 validated records","Removed duplicates and handled missing values","Validated product references, dates, keys, and orphan records","Loaded curated datasets into SQLite","Developed SQL Server loading and validation workflows"],flow:["Raw Data","Extract","Transform","Validate","Load","SQLite / SQL Server"]},
 {id:"retail",n:"02",type:"ETL PIPELINE",title:"Retail ETL Pipeline",desc:"Built an ETL pipeline to extract, transform, validate, and load retail sales data into SQL Server.",tech:["Python","Pandas","SQL Server","PyODBC"],github:"https://github.com/ahmedabozead/Retail_ETL",features:["Removed duplicate records","Handled missing values","Cleaned invalid identifiers and date values","Validated sales values and standardized formats","Connected Python with SQL Server using PyODBC"],flow:["Retail Data","Extract","Pandas","Clean","Validate","SQL Server"]},
 {id:"supermarket",n:"03",type:"ANALYTICS",title:"Supermarket Sales Dashboard",desc:"Developed an interactive Power BI dashboard to analyze supermarket sales data for 2019.",tech:["Power BI","DAX"],github:"https://github.com/ahmedabozead/supermarket-sales-analysis",features:["Total Sales","Total Costs","Gross Income","Branch and city analysis","Product categories","Customer, gender, and time analysis"],flow:["Sales Data","Model","DAX","Dashboard","Insights"]},
 {id:"adidas",n:"04",type:"ANALYTICS",title:"Adidas Sales Dashboard",desc:"Built an interactive Excel dashboard using Power Query and Pivot Tables to analyze products, regions, branches, and sales trends.",tech:["Excel","Power Query","Pivot Tables"],features:["Product analysis","Regional analysis","Branch performance","Sales trends"],flow:["Raw Data","Power Query","Pivot Tables","Dashboard"]},
 {id:"pizza",n:"05",type:"ANALYTICS",title:"Pizza Sales Dashboard",desc:"Created an interactive Power BI dashboard to analyze pizza sales performance.",tech:["Power BI","DAX"],github:"https://github.com/ahmedabozead/pizza-sales-dashboard",features:["Total sales, costs, and profit","Order trends","Product categories","Branch performance","Sales trends"],flow:["Orders","Model","DAX","Dashboard","Performance"]}
];
const skillGroups = [{label:"Programming",icon:Code2,items:["Python","SQL","Bash","Object-Oriented Programming","Data Structures"]},{label:"Databases",icon:Database,items:["SQL Server","PostgreSQL","MySQL","SQLite","Database Design","Stored Procedures","Views","Transactions","Query Optimization","Indexing"]},{label:"Data Engineering",icon:Server,items:["ETL Pipelines","Batch Processing","Data Extraction","Data Transformation","Data Loading","Data Validation","Data Quality","PyODBC","Relational Data Modeling"]},{label:"Processing & Analytics",icon:BarChart3,items:["Pandas","NumPy","Power BI","DAX","Excel","Power Query","Pivot Tables"]}];
const familiar = ["Apache Spark","PySpark","Spark SQL","Apache Airflow","Databricks","dbt","SSIS"];
const workflow = ["SOURCE DATA","EXTRACT","CLEAN","TRANSFORM","VALIDATE","LOAD","DATABASE","ANALYTICS"];
function Reveal({children,delay=0,className=""}:{children:ReactNode;delay?:number;className?:string}) { const ref=useRef(null); const inView=useInView(ref,{once:true,margin:"-70px"}); return <motion.div ref={ref} className={className} initial={{opacity:0,y:22}} animate={inView?{opacity:1,y:0}:{}} transition={{duration:.55,delay,ease:[.23,1,.32,1]}}>{children}</motion.div> }
function Heading({eyebrow,title,text}:{eyebrow:string;title:ReactNode;text?:string}) { return <Reveal><div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div></Reveal> }
function Flow({items,compact=false}:{items:string[];compact?:boolean}) { return <div className={`flow ${compact?"compact":""}`}>{items.map((x,i)=><div className="flow-item" key={x}><div className="flow-node"><span>{String(i+1).padStart(2,"0")}</span>{x}</div>{i<items.length-1&&<ArrowRight size={14}/>}</div>)}</div> }
function ArrowUp(){return <ArrowDownRight size={16} className="link-arrow"/>}
export default function Home(){
 const [scrolled,setScrolled]=useState(false),[menu,setMenu]=useState(false),[active,setActive]=useState<typeof projects[number]|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{const f=()=>setScrolled(scrollY>20);addEventListener("scroll",f);const t=setTimeout(()=>setLoading(false),850);return()=>{removeEventListener("scroll",f);clearTimeout(t)}},[]);
 const nav=["About","Skills","Projects","Experience","Contact"];
 return <><AnimatePresence>{loading&&<motion.div className="loader" exit={{opacity:0}}><div className="loader-mark">A<span>.</span></div><div className="loader-name">Ahmed Abozead<small>Data Engineer</small></div><Flow items={["EXTRACT","TRANSFORM","LOAD"]} compact/></motion.div>}</AnimatePresence>
 <header className={`navbar ${scrolled?"scrolled":""}`}><a className="brand" href="#top"><span className="brand-mark">A<span>.</span></span><span>Ahmed Abozead<small>Data Engineer</small></span></a><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<X/>:<Menu/>}</button><nav className={menu?"open":""}>{nav.map(x=><a key={x} href={`#${x.toLowerCase()}`} onClick={()=>setMenu(false)}>{x}</a>)}<a className="nav-cta" href="#contact">Let's connect <ArrowDownRight size={14}/></a></nav></header>
 <main id="top"><section className="hero"><div className="hero-grid"/><div className="hero-orbit orbit-a"/><div className="hero-orbit orbit-b"/><div className="hero-content"><Reveal><div className="status"><span className="pulse"/> Open to data opportunities <span className="status-line"/></div></Reveal><Reveal delay={.08}><p className="hero-kicker">{`{`} DATA ENGINEERING / 2026 {`}`}</p><h1>Building clarity<br/>from <em>complex data.</em></h1></Reveal><Reveal delay={.16}><p className="hero-copy">Building reliable data pipelines, transforming raw data into clean and structured datasets, and working with Python, SQL, ETL, and relational databases.</p></Reveal><Reveal delay={.24}><div className="hero-actions"><a className="btn btn-primary" href="#projects">View my projects <ArrowDownRight size={16}/></a><a className="btn btn-ghost" href="#contact">Contact me <ArrowDownRight size={16}/></a></div></Reveal><Reveal delay={.3}><div className="socials"><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={15}/> LinkedIn</a><a href={profile.github} target="_blank" rel="noreferrer"><Github size={15}/> GitHub</a></div></Reveal></div><div className="hero-visual"><div className="terminal-card"><div className="terminal-bar"><i/><i/><i/><b>pipeline_flow.py</b></div><div className="terminal-code"><p><em>01</em> <span className="purple">def</span> <span className="green">build_pipeline</span>(data):</p><p><em>02</em> &nbsp; raw = <span className="blue">extract</span>(data)</p><p><em>03</em> &nbsp; clean = <span className="blue">transform</span>(raw)</p><p><em>04</em> &nbsp; valid = <span className="blue">validate</span>(clean)</p><p><em>05</em> &nbsp; <span className="purple">return</span> <span className="blue">load</span>(valid)</p><div className="terminal-result"><Check size={13}/> pipeline completed <span>9,774 rows</span></div></div></div><div className="data-badge badge-one"><Database size={14}/> SQL SERVER</div><div className="data-badge badge-two"><Sparkles size={14}/> DATA QUALITY</div></div><div className="scroll-cue">Scroll to explore <span/></div></section>
 <section className="metrics"><div><strong>05</strong><span>Selected projects</span></div><div><strong>10,003</strong><span>Sales records processed</span></div><div><strong>09<span>,774</span></strong><span>Validated records produced</span></div><div><strong>01</strong><span>Clear engineering mindset</span></div></section>
 <section id="about" className="section about"><div className="about-grid"><Heading eyebrow="01 / ABOUT" title="Engineering with intention." text="I am a Junior Data Engineer focused on turning messy, raw data into reliable datasets that teams can trust."/><Reveal delay={.1}><div className="about-copy"><p>My practical experience comes through hands-on projects in <b>Python, SQL, ETL, data cleaning, data validation, and SQL Server.</b> I build pipelines that extract, transform, validate, and load data into relational databases.</p><p>I am continuously developing my understanding of data warehousing, dimensional modeling, star schemas, incremental loading, CDC, and slowly changing dimensions—without overstating them as professional production experience.</p><div className="signature">Ahmed Abozead<small>Junior Data Engineer · Cairo, Egypt</small></div></div></Reveal></div><Reveal delay={.2}><div className="principles"><div><span>01</span><h3>Reliable by design</h3><p>Validation and data quality checks are part of the pipeline, not an afterthought.</p></div><div><span>02</span><h3>Structured thinking</h3><p>From normalized relational tables to clear transformations and readable SQL.</p></div><div><span>03</span><h3>Always learning</h3><p>Building a foundation across engineering, analytics, and data platforms.</p></div></div></Reveal></section>
 <section id="skills" className="section skills"><Heading eyebrow="02 / CAPABILITIES" title="Tools I work with." text="A practical toolkit for building, validating, and understanding data systems."/><div className="skill-grid">{skillGroups.map((g,i)=><Reveal key={g.label} delay={i*.05}><div className="skill-card"><div className="skill-title"><g.icon size={18}/><h3>{g.label}</h3><span>0{i+1}</span></div><div className="skill-tags">{g.items.map(x=><span key={x}>{x}</span>)}</div></div></Reveal>)}</div><Reveal><div className="familiar"><div><span className="eyebrow">FAMILIAR WITH</span><p>Technologies I am currently learning and exploring.</p></div><div className="familiar-tags">{familiar.map(x=><span key={x}>{x}</span>)}</div></div></Reveal></section>
 <section id="projects" className="section projects"><div className="projects-top"><Heading eyebrow="03 / SELECTED WORK" title="Data, made dependable." text="Projects built to practice the full journey from raw inputs to useful insights."/><div className="project-index">05<small>PROJECTS</small></div></div><div className="project-list">{projects.map((p,i)=><Reveal key={p.id} delay={i*.05}><article className="project-card"><div className="project-meta"><span>{p.n}</span><span>{p.type}</span></div><div className="project-main"><div><h3>{p.title}</h3><p>{p.desc}</p><div className="tech-list">{p.tech.map(x=><span key={x}>{x}</span>)}</div></div><div className="project-actions">{p.github&&<a className="icon-link" href={p.github} target="_blank" rel="noreferrer"><Github size={17}/></a>}<button className="details-btn" onClick={()=>setActive(p)}>View details <ArrowRight size={15}/></button></div></div><Flow items={p.flow} compact={p.id!=="sales"}/></article></Reveal>)}</div></section>
 <section className="workflow section"><Heading eyebrow="04 / HOW I WORK WITH DATA" title="Data should move with purpose." text="A clear workflow from source data to analytics—designed around transformation, validation, and trust."/><Reveal><div className="workflow-board"><div className="workflow-line"/>{workflow.map((x,i)=><div className="workflow-step" key={x}><div className="workflow-dot">{String(i+1).padStart(2,"0")}</div><strong>{x}</strong></div>)}</div></Reveal></section>
 <section id="experience" className="section experience"><Heading eyebrow="05 / EXPERIENCE" title="Teaching with clarity."/><div className="timeline"><Reveal><div className="timeline-item"><div className="timeline-date">SEP 2024<br/><span>— SEP 2025</span></div><div className="timeline-dot"/><div><span className="eyebrow">EDUCATIONAL CENTER</span><h3>Technology Instructor</h3><p>Delivered technology courses covering basic computing, digital literacy, and problem-solving skills. Designed and delivered interactive lessons, explained technical concepts clearly, and adapted lessons to different learning levels.</p></div></div></Reveal><Reveal delay={.12}><div className="timeline-item"><div className="timeline-date">SEP 2021<br/><span>— JUN 2025</span></div><div className="timeline-dot"/><div><span className="eyebrow">EDUCATION</span><h3>Bachelor of Computer and Information Technology</h3><p>Kafr El-Sheikh University</p></div></div></Reveal></div></section>
 <section id="contact" className="section contact"><div className="contact-grid"><div><Heading eyebrow="06 / CONTACT" title={<>Let's build something<br/><em>reliable.</em></>} text="Have a data project or opportunity in mind? Let's connect."/><div className="contact-links"><a href={`mailto:${profile.email}`}><Mail size={17}/><span>Email<small>{profile.email}</small></span><ArrowUp/></a><a href={`tel:${profile.phone}`}><Phone size={17}/><span>Phone<small>{profile.phone}</small></span><ArrowUp/></a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={17}/><span>LinkedIn<small>/ahmed-abozead</small></span><ArrowUp/></a><a href={profile.github} target="_blank" rel="noreferrer"><Github size={17}/><span>GitHub<small>/ahmedabozead</small></span><ArrowUp/></a></div></div><Reveal delay={.12}><form className="contact-form" action="https://formsubmit.co/ahmednb34963@gmail.com" method="POST"><input type="hidden" name="_subject" value="New message from Ahmed Abozead Portfolio"/><input type="hidden" name="_template" value="table"/><input type="hidden" name="_captcha" value="false"/><input type="hidden" name="_next" value="https://ahmedabozead.github.io/ahmed-abozead-portfolio/#contact"/><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input type="email" name="email" required placeholder="you@email.com"/></label><label>Message<textarea name="message" required rows={5} placeholder="Tell me a little about your project..."/></label><button className="btn btn-primary" type="submit">Send message <Send size={15}/></button><p className="form-note">Your message will be sent directly to Ahmed's email.</p></form></Reveal></div></section></main>
 <footer><div className="footer-brand"><span className="brand-mark">A<span>.</span></span><div><strong>Ahmed Abozead</strong><small>Data Engineer</small></div></div><p>Cairo, Egypt · © 2026 Ahmed Abozead. All rights reserved.</p><div className="footer-links"><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href={profile.github} target="_blank" rel="noreferrer">GitHub</a><a href={`mailto:${profile.email}`}>Email</a></div></footer>
 <AnimatePresence>{active&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setActive(null)}><motion.div className="project-modal" initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setActive(null)}><X/></button><span className="eyebrow">{active.n} / {active.type}</span><h2>{active.title}</h2><p>{active.desc}</p><h4>Key features</h4><ul>{active.features.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><Flow items={active.flow}/>{active.github&&<a className="btn btn-primary" href={active.github} target="_blank" rel="noreferrer">Open on GitHub <ExternalLink size={15}/></a>}</motion.div></motion.div>}</AnimatePresence></>;
}